(function(A){function L(a,c){a=Object.create(a);for(var b in c)a[b]=c[b];c.toString!==Object.prototype.toString&&(a.toString=c.toString);return a}function T(a,c){if(null==c)return null;null==c.__id__&&(c.__id__=A.$haxeUID++);var b;null==a.hx__closures__?a.hx__closures__={}:b=a.hx__closures__[c.__id__];null==b&&(b=c.bind(a),a.hx__closures__[c.__id__]=b);return b}var w=function(){return q.__string_rec(this,"")},H=H||{},I,M=function(a,c){this.r=new RegExp(a,c.split("u").join(""))};M.__name__=!0;M.prototype=
{match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m}};var n=function(){};n.__name__=!0;n.substr=function(a,c,b){if(null==b)b=a.length;else if(0>b)if(0==c)b=a.length+b;else return"";return a.substr(c,b)};n.now=function(){return Date.now()};var N=function(){};N.__name__=!0;N.exists=function(a,c){a=a instanceof Array?new O(a):a.iterator();for(;a.hasNext();){var b=a.next();if(c(b))return!0}return!1};var P=function(){};P.__name__=!0;var J=function(a,
c){this.shapes=[];this.shapes=a;a=a[0];if(1!=a.type)var b=a=0;else b=a.data,a=h.get_x2(b)-h.get_x1(b),b=h.get_y2(b)-h.get_y1(b);this.renderer=new Q(c,a,b)};J.__name__=!0;var R=function(){};R.__name__=!0;R.main=function(){for(var a,c,b=[],d=window.document.documentElement.getElementsByClassName("geometrize_widget"),g=0;g<d.length;)a=d[g],++g,c=a.attributes.getNamedItem("data-embedded"),null!=c&&(c=c.value,0!=c.length&&(a=a.id,c=B.shapesFromJson(c),a=new J(c,a),a.renderer.render(a.shapes),b.push(a)));
for(g=0;g<d.length;)if(a=d[g],++g,c=a.attributes.getNamedItem("data-source"),null!=c&&(c=c.value,0!=c.length)){a=[a.id];var f=new U(c);f=S.toVarName(f.file+"_"+f.ext);Object.prototype.hasOwnProperty.call(P,f)?(c=r.field(P,f),a=new J(c,a[0]),a.renderer.render(a.shapes),b.push(a)):(c=new K(c),c.onData=function(a){return function(c){c=B.shapesFromJson(c);c=new J(c,a[0]);c.renderer.render(c.shapes);b.push(c)}}(a),c.onError=function(){return function(a){console.log("Main.hx:177:",a)}}(),c.request())}};
Math.__name__=!0;var r=function(){};r.__name__=!0;r.field=function(a,c){try{return a[c]}catch(b){return null}};r.isFunction=function(a){return"function"==typeof a?!(a.__name__||a.__ename__):!1};r.compareMethods=function(a,c){return a==c?!0:r.isFunction(a)&&r.isFunction(c)?a.scope==c.scope&&a.method==c.method?null!=a.method:!1:!1};var C=function(){};C.__name__=!0;C.string=function(a){return q.__string_rec(a,"")};var x=function(){};x.__name__=!0;x.replace=function(a,c,b){return a.split(c).join(b)};
var l=function(a,c,b){Error.call(this,a);this.message=a;this.__previousException=c;this.__nativeException=null!=b?b:this};l.__name__=!0;l.caught=function(a){return a instanceof l?a:a instanceof Error?new l(a.message,null,a):new D(a,null,a)};l.thrown=function(a){return a instanceof l?a.get_native():a instanceof Error?a:new D(a)};l.__super__=Error;l.prototype=L(Error.prototype,{unwrap:function(){return this.__nativeException},get_native:function(){return this.__nativeException}});var D=function(a,c,
b){l.call(this,String(a),c,b);this.value=a};D.__name__=!0;D.__super__=l;D.prototype=L(l.prototype,{unwrap:function(){return this.value}});var E=function(a){this.url=a;this.headers=[];this.params=[];this.emptyOnData=T(this,this.onData)};E.__name__=!0;E.prototype={onData:function(a){},onBytes:function(a){},onError:function(a){},onStatus:function(a){},hasOnData:function(){return!r.compareMethods(T(this,this.onData),this.emptyOnData)},success:function(a){this.responseBytes=a;this.responseAsString=null;
if(this.hasOnData())this.onData(this.get_responseData());this.onBytes(this.responseBytes)},get_responseData:function(){null==this.responseAsString&&null!=this.responseBytes&&(this.responseAsString=this.responseBytes.getString(0,this.responseBytes.length,F.UTF8));return this.responseAsString}};var K=function(a){this.async=!0;this.withCredentials=!1;E.call(this,a)};K.__name__=!0;K.__super__=E;K.prototype=L(E.prototype,{request:function(a){var c=this;this.responseBytes=this.responseAsString=null;var b=
this.req=G.createXMLHttpRequest(),d=function(a){if(4==b.readyState){try{var d=b.status}catch(X){d=null}0==d&&G.get_supported()&&null!=A.location&&(a=A.location.protocol.toLowerCase(),(new M("^(?:about|app|app-storage|.+-extension|file|res|widget):$","")).match(a)&&(d=null!=b.response?200:404));void 0==d&&(d=null);if(null!=d)c.onStatus(d);if(null!=d&&200<=d&&400>d)c.req=null,c.success(v.ofData(b.response));else if(null==d||0==d&&null==b.response)c.req=null,c.onError("Failed to connect or resolve host");
else if(null==d)c.req=null,d=null!=b.response?v.ofData(b.response):null,c.responseBytes=d,c.onError("Http Error #"+b.status);else switch(d){case 12007:c.req=null;c.onError("Unknown host");break;case 12029:c.req=null;c.onError("Failed to connect to host");break;default:c.req=null,d=null!=b.response?v.ofData(b.response):null,c.responseBytes=d,c.onError("Http Error #"+b.status)}}};this.async&&(b.onreadystatechange=d);var g=this.postData;var f=this.postBytes;var e=null==g?null==f?null:new Blob([f.b.bufferValue]):
null==f?g:null;if(null!=e)a=!0;else for(g=0,f=this.params;g<f.length;){var h=f[g];++g;e=null==e?"":(null==e?"null":C.string(e))+"&";var k=h.name;e=(null==e?"null":C.string(e))+encodeURIComponent(k)+"="+encodeURIComponent(h.value)}try{if(a)b.open("POST",this.url,this.async);else if(null!=e){var m=1>=this.url.split("?").length;b.open("GET",this.url+(m?"?":"&")+(null==e?"null":C.string(e)),this.async);e=null}else b.open("GET",this.url,this.async);b.responseType="arraybuffer"}catch(V){f=l.caught(V).unwrap();
this.req=null;this.onError(f.toString());return}b.withCredentials=this.withCredentials;!N.exists(this.headers,function(a){return"Content-Type"==a.name})&&a&&null==this.postData&&b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");g=0;for(f=this.headers;g<f.length;)a=f[g],++g,b.setRequestHeader(a.name,a.value);b.send(e);this.async||d(null)}});var v=function(a){this.length=a.byteLength;this.b=new Uint8Array(a);this.b.bufferValue=a;a.hxBytes=this;a.bytes=this.b};v.__name__=!0;v.ofData=
function(a){var c=a.hxBytes;return null!=c?c:new v(a)};v.prototype={getString:function(a,c,b){if(0>a||0>c||a+c>this.length)throw l.thrown(y.OutsideBounds);null==b&&(b=F.UTF8);var d="",g=this.b,f=a;a+=c;switch(b._hx_index){case 0:for(;f<a;){b=g[f++];if(128>b){if(0==b)break}else if(224>b)b=(b&63)<<6|g[f++]&127;else if(240>b)c=g[f++],b=(b&31)<<12|(c&127)<<6|g[f++]&127;else{c=g[f++];var e=g[f++];b=(b&15)<<18|(c&127)<<12|(e&127)<<6|g[f++]&127}d+=String.fromCodePoint(b)}break;case 1:for(;f<a;)b=g[f++]|
g[f++]<<8,d+=String.fromCodePoint(b)}return d}};var F=H["haxe.io.Encoding"]={__ename__:!0,__constructs__:null,UTF8:{_hx_name:"UTF8",_hx_index:0,__enum__:"haxe.io.Encoding",toString:w},RawNative:{_hx_name:"RawNative",_hx_index:1,__enum__:"haxe.io.Encoding",toString:w}};F.__constructs__=[F.UTF8,F.RawNative];var y=H["haxe.io.Error"]={__ename__:!0,__constructs__:null,Blocked:{_hx_name:"Blocked",_hx_index:0,__enum__:"haxe.io.Error",toString:w},Overflow:{_hx_name:"Overflow",_hx_index:1,__enum__:"haxe.io.Error",
toString:w},OutsideBounds:{_hx_name:"OutsideBounds",_hx_index:2,__enum__:"haxe.io.Error",toString:w},Custom:(I=function(a){return{_hx_index:3,e:a,__enum__:"haxe.io.Error",toString:w}},I._hx_name="Custom",I.__params__=["e"],I)};y.__constructs__=[y.Blocked,y.Overflow,y.OutsideBounds,y.Custom];var U=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var c=a.lastIndexOf("/"),b=a.lastIndexOf("\\");c<b?(this.dir=n.substr(a,0,b),a=n.substr(a,b+1,null),this.backslash=!0):b<c?(this.dir=
n.substr(a,0,c),a=n.substr(a,c+1,null)):this.dir=null;c=a.lastIndexOf(".");-1!=c?(this.ext=n.substr(a,c+1,null),this.file=n.substr(a,0,c)):(this.ext=null,this.file=a)};U.__name__=!0;var O=function(a){this.current=0;this.array=a};O.__name__=!0;O.prototype={hasNext:function(){return this.current<this.array.length},next:function(){return this.array[this.current++]}};var q=function(){};q.__name__=!0;q.__string_rec=function(a,c){if(null==a)return"null";if(5<=c.length)return"<...>";var b=typeof a;"function"==
b&&(a.__name__||a.__ename__)&&(b="object");switch(b){case "function":return"<function>";case "object":if(a.__enum__){var d=H[a.__enum__].__constructs__[a._hx_index];b=d._hx_name;if(d.__params__){c+="\t";var e=[],f=0;for(d=d.__params__;f<d.length;){var h=d[f];f+=1;e.push(q.__string_rec(a[h],c))}return b+"("+e.join(",")+")"}return b}if(a instanceof Array){b="[";c+="\t";e=0;for(f=a.length;e<f;)d=e++,b+=(0<d?",":"")+q.__string_rec(a[d],c);return b+"]"}try{e=a.toString}catch(W){return"???"}if(null!=e&&
e!=Object.toString&&"function"==typeof e&&(b=a.toString(),"[object Object]"!=b))return b;b="{\n";c+="\t";e=null!=a.hasOwnProperty;f=null;for(f in a)e&&!a.hasOwnProperty(f)||"prototype"==f||"__class__"==f||"__super__"==f||"__interfaces__"==f||"__properties__"==f||(2!=b.length&&(b+=", \n"),b+=c+f+" : "+q.__string_rec(a[f],c));c=c.substring(1);return b+("\n"+c+"}");case "string":return a;default:return String(a)}};var G=function(){};G.__name__=!0;G.get_supported=function(){return"undefined"!=typeof window&&
"undefined"!=typeof window.location?"string"==typeof window.location.protocol:!1};G.createXMLHttpRequest=function(){if("undefined"!=typeof XMLHttpRequest)return new XMLHttpRequest;if("undefined"!=typeof ActiveXObject)return new ActiveXObject("Microsoft.XMLHTTP");throw l.thrown("Unable to create XMLHttpRequest object.");};var S=function(){};S.__name__=!0;S.toVarName=function(a){return x.replace(x.replace(x.replace(x.replace(a,"/","_"),".","_")," ","_"),"-","_")};var B=function(){};B.__name__=!0;B.shapeDataFromJson=
function(a){return JSON.parse(a).shapes};B.shapesFromJson=function(a){a=JSON.parse(a).shapes;for(var c=[],b=0;b<a.length;){var d=a[b];++b;var e=d.color;c.push({type:d.type,color:(((e[0]|0)&255)<<24)+(((e[1]|0)&255)<<16)+(((e[2]|0)&255)<<8)+((e[3]|0)&255),data:d.data})}return c};var Q=function(a,c,b){a=window.document.getElementById(a);this.canvas=window.document.createElement("canvas");this.canvas.width=c;this.canvas.height=b;this.canvas.className="geometrize_canvas";this.ctx=this.canvas.getContext("2d",
null);a.appendChild(this.canvas)};Q.__name__=!0;Q.prototype={render:function(a){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);for(var c=0;c<a.length;){var b=a[c];++c;switch(b.type){case 1:var d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.fillRect(h.get_x1(d),h.get_y1(d),h.get_x2(d)-h.get_x1(d),h.get_y2(d)-h.get_y1(d));break;case 2:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>
8&255)+","+(b&255)/255+")";this.ctx.save();this.ctx.translate(e.get_x1(d)+(e.get_x2(d)-e.get_x1(d))/2,e.get_y1(d)+(e.get_y2(d)-e.get_y1(d))/2);this.ctx.rotate(e.get_angle(d)*(Math.PI/180));this.ctx.fillRect(-(e.get_x2(d)-e.get_x1(d))/2,-(e.get_y2(d)-e.get_y1(d))/2,e.get_x2(d)-e.get_x1(d),e.get_y2(d)-e.get_y1(d));this.ctx.restore();break;case 4:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(k.get_x1(d),
k.get_y1(d));this.ctx.lineTo(k.get_x2(d),k.get_y2(d));this.ctx.lineTo(k.get_x3(d),k.get_y3(d));this.ctx.lineTo(k.get_x1(d),k.get_y1(d));this.ctx.fill();break;case 8:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.ellipse(t.get_x(d),t.get_y(d),t.get_rx(d),t.get_ry(d),0,0,360);this.ctx.fill();break;case 16:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+
")";this.ctx.beginPath();this.ctx.ellipse(p.get_x(d),p.get_y(d),p.get_rx(d),p.get_ry(d),p.get_angle(d)*(Math.PI/180),0,360);this.ctx.fill();break;case 32:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.arc(z.get_x(d),z.get_y(d),z.get_r(d),0,2*Math.PI);this.ctx.fill();break;case 64:d=b.data;b=b.color;this.ctx.strokeStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();
this.ctx.moveTo(u.get_x1(d),u.get_y1(d));this.ctx.lineTo(u.get_x2(d),u.get_y2(d));this.ctx.stroke();break;case 128:d=b.data;b=b.color;this.ctx.strokeStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(m.get_x1(d),m.get_y1(d));this.ctx.quadraticCurveTo(m.get_cx(d),m.get_cy(d),m.get_x2(d),m.get_y2(d));this.ctx.stroke();break;case 256:d=b.data;b=b.color;this.ctx.strokeStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+
")";this.ctx.beginPath();for(b=0;b<d.length-1;)this.ctx.lineTo(d[b],d[b+1]),b+=2;this.ctx.stroke();break;default:throw l.thrown("Encountered unsupported shape type");}}},drawRectangle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.fillRect(h.get_x1(a),h.get_y1(a),h.get_x2(a)-h.get_x1(a),h.get_y2(a)-h.get_y1(a))},drawRotatedRectangle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+
")";this.ctx.save();this.ctx.translate(e.get_x1(a)+(e.get_x2(a)-e.get_x1(a))/2,e.get_y1(a)+(e.get_y2(a)-e.get_y1(a))/2);this.ctx.rotate(e.get_angle(a)*(Math.PI/180));this.ctx.fillRect(-(e.get_x2(a)-e.get_x1(a))/2,-(e.get_y2(a)-e.get_y1(a))/2,e.get_x2(a)-e.get_x1(a),e.get_y2(a)-e.get_y1(a));this.ctx.restore()},drawTriangle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(k.get_x1(a),k.get_y1(a));this.ctx.lineTo(k.get_x2(a),
k.get_y2(a));this.ctx.lineTo(k.get_x3(a),k.get_y3(a));this.ctx.lineTo(k.get_x1(a),k.get_y1(a));this.ctx.fill()},drawEllipse:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.ellipse(t.get_x(a),t.get_y(a),t.get_rx(a),t.get_ry(a),0,0,360);this.ctx.fill()},drawRotatedEllipse:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.ellipse(p.get_x(a),
p.get_y(a),p.get_rx(a),p.get_ry(a),p.get_angle(a)*(Math.PI/180),0,360);this.ctx.fill()},drawCircle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.arc(z.get_x(a),z.get_y(a),z.get_r(a),0,2*Math.PI);this.ctx.fill()},drawLine:function(a,c){this.ctx.strokeStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(u.get_x1(a),u.get_y1(a));this.ctx.lineTo(u.get_x2(a),
u.get_y2(a));this.ctx.stroke()},drawQuadraticBezier:function(a,c){this.ctx.strokeStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(m.get_x1(a),m.get_y1(a));this.ctx.quadraticCurveTo(m.get_cx(a),m.get_cy(a),m.get_x2(a),m.get_y2(a));this.ctx.stroke()},drawPolyline:function(a,c){this.ctx.strokeStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();for(c=0;c<a.length-1;)this.ctx.lineTo(a[c],a[c+
1]),c+=2;this.ctx.stroke()}};var z={get_x:function(a){return a[0]},get_y:function(a){return a[1]},get_r:function(a){return a[2]}},t={get_x:function(a){return a[0]},get_y:function(a){return a[1]},get_rx:function(a){return a[2]},get_ry:function(a){return a[3]}},u={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]}},m={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_cx:function(a){return a[2]},get_cy:function(a){return a[3]},
get_x2:function(a){return a[4]},get_y2:function(a){return a[5]}},h={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]}},p={get_x:function(a){return a[0]},get_y:function(a){return a[1]},get_rx:function(a){return a[2]},get_ry:function(a){return a[3]},get_angle:function(a){return a[4]}},e={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]},get_angle:function(a){return a[4]}},
k={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]},get_x3:function(a){return a[4]},get_y3:function(a){return a[5]}};A.$haxeUID|=0;"undefined"!=typeof performance&&"function"==typeof performance.now&&(n.now=performance.now.bind(performance));null==String.fromCodePoint&&(String.fromCodePoint=function(a){return 65536>a?String.fromCharCode(a):String.fromCharCode((a>>10)+55232)+String.fromCharCode((a&1023)+56320)});String.__name__=
!0;Array.__name__=!0;q.__toStr={}.toString;R.main()})("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
