sudo: required
dist: trusty

language: haxe

os:
  - linux

# see haxe versions: http://haxe.org/website-content/downloads/versions.json
haxe:
  - "3.4.2"

# Add encrypted API key
env:
  global:
    - secure: ljp1h0q5JTmM32ICccHEWLpN00Ru7Ri6R2lt0OYjuEoyqyRD2S/S6L9/QUhNPlaHBxGTiHEWtJjM7lDUd6G76TC1N/mZOhqvwyv04YSn6lswiDh33UN8GL5UHDpJHFsoL7EJaQA3OhxyzFDAwGrbN+3N3LVbmvQCrdewAUSW1wOpDHVVtV74BMIC4kp5YF2YC4LVIHfRwjMxRh8mcx+opRYucQST6ywDKu+b92iRHwvUsYy1J4ESRh1t4aDY+l5fcyTO2kDkzOgZqm3/jN2ytdOSP0vanot+YJwQHo4shIOsmW7l2lrOEWEwDuzDmD1Nz6INTJkOxyPxBYzWu0NNI2NkVkDfU8aaggLlHfDv79OMDyXWDzHGFskz6efjn6tTXUdWGjGbdrgpvwySR9Lle/6V7dy5iGWqmDr6WBwNaJqGvAibowSFmsnhJujIp8DMYgU6jR7drLI9BzTAXKWOHPn6jLC4+rN7qCVBUvk6IswZpGEWfRqZBsI5AA906XOo+zVR69hCIcFWQ9mV8nN+unFwtZCjnoJjYoFSMO/qd6bzLb5BTu5DYkcdcYSrEiAR8ybAHQjh0IH2E3Z9AAjH/2z1f/hMIUsxdIV5XKLUr8GLRasZRyjXC8uB6fxJATuokNXgTUhvJwaPC7NCLAwLYsTRSU2SWde3sPyPUlZe5iw=

# Blacklist
branches:
  only:
    - master

# Build the code
script:
  - haxe GeometrizeWebExport.hxml release.hxml

# Deploy the test configuration using Travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/test/
  github_token: $GITHUB_API_KEY
  on:
    branch: master