(function(){var y=function(a,c){this.r=new RegExp(a,c.split("u").join(""))};y.prototype={match:function(a){this.r.global&&(this.r.lastIndex=0);this.r.m=this.r.exec(a);this.r.s=a;return null!=this.r.m}};var p=function(){};p.substr=function(a,c,b){if(null==b)b=a.length;else if(0>b)if(0==c)b=a.length+b;else return"";return a.substr(c,b)};var z=function(){};z.exists=function(a,c){for(a=a.iterator();a.hasNext();){var b=a.next();if(c(b))return!0}return!1};var v=function(){this.length=0};v.prototype={iterator:function(){return new A(this.h)}};
var A=function(a){this.head=a};A.prototype={hasNext:function(){return null!=this.head},next:function(){var a=this.head.item;this.head=this.head.next;return a}};var B=function(){},w=function(a,c){this.shapes=[];this.shapes=a;a=a[0];if(1!=a.type)var b=a=0;else b=a.data,a=f.get_x2(b)-f.get_x1(b),b=f.get_y2(b)-f.get_y1(b);this.renderer=new C(c,a,b)},x=function(){this.widgets=[];for(var a=window.document.documentElement.getElementsByClassName("geometrize_widget"),c=0;c<a.length;){var b=a[c];++c;var d=
b.attributes.getNamedItem("data-embedded");null!=d&&(d=d.value,0!=d.length&&(b=b.id,d=t.shapesFromJson(d),b=new w(d,b),b.renderer.render(b.shapes),this.widgets.push(b)))}for(c=0;c<a.length;)if(b=a[c],++c,d=b.attributes.getNamedItem("data-source"),null!=d&&(d=d.value,0!=d.length)){b=[b.id];var e=[this],f=new H(d);f=D.toVarName(f.file+"_"+f.ext);Object.prototype.hasOwnProperty.call(B,f)?(d=E.field(B,f),b=new w(d,b[0]),b.renderer.render(b.shapes),this.widgets.push(b)):(d=new F(d),d.onData=function(a,
b){return function(c){c=t.shapesFromJson(c);c=new w(c,b[0]);c.renderer.render(c.shapes);a[0].widgets.push(c)}}(e,b),d.onError=function(){return function(a){console.log(a)}}(),d.request())}};x.main=function(){new x};var E=function(){};E.field=function(a,c){try{return a[c]}catch(b){return null}};var r=function(){};r.replace=function(a,c,b){return a.split(c).join(b)};var F=function(a){this.url=a;this.headers=new v;this.params=new v;this.async=!0;this.withCredentials=!1};F.prototype={request:function(a){var c=
this;c.responseData=null;var b=this.req=G.createXMLHttpRequest(),d=function(a){if(4==b.readyState){try{var d=b.status}catch(I){d=null}null!=d&&"undefined"!==typeof window&&(a=window.location.protocol.toLowerCase(),(new y("^(?:about|app|app-storage|.+-extension|file|res|widget):$","")).match(a)&&(d=null!=b.responseText?200:404));void 0==d&&(d=null);if(null!=d)c.onStatus(d);if(null!=d&&200<=d&&400>d)c.req=null,c.onData(c.responseData=b.responseText);else if(null==d)c.req=null,c.onError("Failed to connect or resolve host");
else switch(d){case 12007:c.req=null;c.onError("Unknown host");break;case 12029:c.req=null;c.onError("Failed to connect to host");break;default:c.req=null,c.responseData=b.responseText,c.onError("Http Error #"+b.status)}}};this.async&&(b.onreadystatechange=d);var e=this.postData;if(null!=e)a=!0;else for(var f=this.params.h;null!=f;){var g=f.item;f=f.next;e=null==e?"":e+"&";var h=encodeURIComponent(g.param)+"=";e+=h+encodeURIComponent(g.value)}try{if(a)b.open("POST",this.url,this.async);else if(null!=
e){var k=1>=this.url.split("?").length;b.open("GET",this.url+(k?"?":"&")+e,this.async);e=null}else b.open("GET",this.url,this.async)}catch(u){u instanceof l&&(u=u.val);c.req=null;this.onError(u.toString());return}b.withCredentials=this.withCredentials;!z.exists(this.headers,function(a){return"Content-Type"==a.header})&&a&&null==this.postData&&b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");for(a=this.headers.h;null!=a;)f=a.item,a=a.next,b.setRequestHeader(f.header,f.value);
b.send(e);this.async||d(null)},onData:function(a){},onError:function(a){},onStatus:function(a){}};var H=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var c=a.lastIndexOf("/"),b=a.lastIndexOf("\\");c<b?(this.dir=p.substr(a,0,b),a=p.substr(a,b+1,null),this.backslash=!0):b<c?(this.dir=p.substr(a,0,c),a=p.substr(a,c+1,null)):this.dir=null;c=a.lastIndexOf(".");-1!=c?(this.ext=p.substr(a,c+1,null),this.file=p.substr(a,0,c)):(this.ext=null,this.file=a)},l=function(a){Error.call(this);
this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,l)};l.wrap=function(a){return a instanceof Error?a:new l(a)};l.__super__=Error;l.prototype=function(a,c){function b(){}b.prototype=a;a=new b;for(var d in c)a[d]=c[d];c.toString!==Object.prototype.toString&&(a.toString=c.toString);return a}(Error.prototype,{});var G=function(){};G.createXMLHttpRequest=function(){if("undefined"!=typeof XMLHttpRequest)return new XMLHttpRequest;if("undefined"!=typeof ActiveXObject)return new ActiveXObject("Microsoft.XMLHTTP");
throw new l("Unable to create XMLHttpRequest object.");};var D=function(){};D.toVarName=function(a){return r.replace(r.replace(r.replace(r.replace(a,"/","_"),".","_")," ","_"),"-","_")};var t=function(){};t.shapeDataFromJson=function(a){return JSON.parse(a).shapes};t.shapesFromJson=function(a){a=JSON.parse(a).shapes;for(var c=[],b=0;b<a.length;){var d=a[b];++b;var e=d.color;c.push({type:d.type,color:(((e[0]|0)&255)<<24)+(((e[1]|0)&255)<<16)+(((e[2]|0)&255)<<8)+((e[3]|0)&255),data:d.data})}return c};
var C=function(a,c,b){a=window.document.getElementById(a);this.canvas=window.document.createElement("canvas");this.canvas.width=c;this.canvas.height=b;this.canvas.className="geometrize_canvas";this.ctx=this.canvas.getContext("2d",null);a.appendChild(this.canvas)};C.prototype={render:function(a){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);for(var c=0;c<a.length;){var b=a[c];++c;switch(b.type){case 1:var d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+
(b>>8&255)+","+(b&255)/255+")";this.ctx.fillRect(f.get_x1(d),f.get_y1(d),f.get_x2(d)-f.get_x1(d),f.get_y2(d)-f.get_y1(d));break;case 2:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.save();this.ctx.translate(e.get_x1(d)+(e.get_x2(d)-e.get_x1(d))/2,e.get_y1(d)+(e.get_y2(d)-e.get_y1(d))/2);this.ctx.rotate(e.get_angle(d)*(Math.PI/180));this.ctx.fillRect(-(e.get_x2(d)-e.get_x1(d))/2,-(e.get_y2(d)-e.get_y1(d))/2,e.get_x2(d)-e.get_x1(d),
e.get_y2(d)-e.get_y1(d));this.ctx.restore();break;case 4:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(g.get_x1(d),g.get_y1(d));this.ctx.lineTo(g.get_x2(d),g.get_y2(d));this.ctx.lineTo(g.get_x3(d),g.get_y3(d));this.ctx.lineTo(g.get_x1(d),g.get_y1(d));this.ctx.fill();break;case 8:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();
this.ctx.ellipse(m.get_x(d),m.get_y(d),m.get_rx(d),m.get_ry(d),0,0,360);this.ctx.fill();break;case 16:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.ellipse(k.get_x(d),k.get_y(d),k.get_rx(d),k.get_ry(d),k.get_angle(d)*(Math.PI/180),0,360);this.ctx.fill();break;case 32:d=b.data;b=b.color;this.ctx.fillStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.arc(q.get_x(d),
q.get_y(d),q.get_r(d),0,2*Math.PI);this.ctx.fill();break;case 64:d=b.data;b=b.color;this.ctx.strokeStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(n.get_x1(d),n.get_y1(d));this.ctx.lineTo(n.get_x2(d),n.get_y2(d));this.ctx.stroke();break;case 128:d=b.data;b=b.color;this.ctx.strokeStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(h.get_x1(d),h.get_y1(d));this.ctx.quadraticCurveTo(h.get_cx(d),
h.get_cy(d),h.get_x2(d),h.get_y2(d));this.ctx.stroke();break;case 256:d=b.data;b=b.color;this.ctx.strokeStyle="rgba("+(b>>24&255)+","+(b>>16&255)+","+(b>>8&255)+","+(b&255)/255+")";this.ctx.beginPath();for(b=0;b<d.length-1;)this.ctx.lineTo(d[b],d[b+1]),b+=2;this.ctx.stroke();break;default:throw new l("Encountered unsupported shape type");}}},drawRectangle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.fillRect(f.get_x1(a),f.get_y1(a),
f.get_x2(a)-f.get_x1(a),f.get_y2(a)-f.get_y1(a))},drawRotatedRectangle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.save();this.ctx.translate(e.get_x1(a)+(e.get_x2(a)-e.get_x1(a))/2,e.get_y1(a)+(e.get_y2(a)-e.get_y1(a))/2);this.ctx.rotate(e.get_angle(a)*(Math.PI/180));this.ctx.fillRect(-(e.get_x2(a)-e.get_x1(a))/2,-(e.get_y2(a)-e.get_y1(a))/2,e.get_x2(a)-e.get_x1(a),e.get_y2(a)-e.get_y1(a));this.ctx.restore()},drawTriangle:function(a,
c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(g.get_x1(a),g.get_y1(a));this.ctx.lineTo(g.get_x2(a),g.get_y2(a));this.ctx.lineTo(g.get_x3(a),g.get_y3(a));this.ctx.lineTo(g.get_x1(a),g.get_y1(a));this.ctx.fill()},drawEllipse:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.ellipse(m.get_x(a),m.get_y(a),m.get_rx(a),m.get_ry(a),0,0,360);
this.ctx.fill()},drawRotatedEllipse:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.ellipse(k.get_x(a),k.get_y(a),k.get_rx(a),k.get_ry(a),k.get_angle(a)*(Math.PI/180),0,360);this.ctx.fill()},drawCircle:function(a,c){this.ctx.fillStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.arc(q.get_x(a),q.get_y(a),q.get_r(a),0,2*Math.PI);this.ctx.fill()},drawLine:function(a,
c){this.ctx.strokeStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(n.get_x1(a),n.get_y1(a));this.ctx.lineTo(n.get_x2(a),n.get_y2(a));this.ctx.stroke()},drawQuadraticBezier:function(a,c){this.ctx.strokeStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();this.ctx.moveTo(h.get_x1(a),h.get_y1(a));this.ctx.quadraticCurveTo(h.get_cx(a),h.get_cy(a),h.get_x2(a),h.get_y2(a));this.ctx.stroke()},drawPolyline:function(a,
c){this.ctx.strokeStyle="rgba("+(c>>24&255)+","+(c>>16&255)+","+(c>>8&255)+","+(c&255)/255+")";this.ctx.beginPath();for(c=0;c<a.length-1;)this.ctx.lineTo(a[c],a[c+1]),c+=2;this.ctx.stroke()}};var q={get_x:function(a){return a[0]},get_y:function(a){return a[1]},get_r:function(a){return a[2]}},m={get_x:function(a){return a[0]},get_y:function(a){return a[1]},get_rx:function(a){return a[2]},get_ry:function(a){return a[3]}},n={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},
get_y2:function(a){return a[3]}},h={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_cx:function(a){return a[2]},get_cy:function(a){return a[3]},get_x2:function(a){return a[4]},get_y2:function(a){return a[5]}},f={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]}},k={get_x:function(a){return a[0]},get_y:function(a){return a[1]},get_rx:function(a){return a[2]},get_ry:function(a){return a[3]},get_angle:function(a){return a[4]}},
e={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]},get_angle:function(a){return a[4]}},g={get_x1:function(a){return a[0]},get_y1:function(a){return a[1]},get_x2:function(a){return a[2]},get_y2:function(a){return a[3]},get_x3:function(a){return a[4]},get_y3:function(a){return a[5]}};x.main()})();
